// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bawrukrvaihypvsiajiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhd3J1a3J2YWloeXB2c2lhaml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzY1MjYsImV4cCI6MjA1NjUxMjUyNn0.iFxImD6jgpTTxKPE25AS3nTxB1pEm_Ae1CvCIY8XCdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);